openapi: 3.0.3
info:
  title: Personal Website API
  description: |
    API documentation for Jeff Bridwell's personal website.
    Includes endpoints for blog management, gallery operations, and media handling.
  version: 1.0.0
  contact:
    name: Jeff Bridwell

servers:
  - url: http://localhost:8081
    description: Development server

tags:
  - name: Gallery
    description: Image gallery and media management endpoints
  - name: Blog
    description: Blog post management endpoints
  - name: Media
    description: Media processing and serving endpoints

paths:
  /gallery/images:
    get:
      summary: List gallery images
      description: Returns a paginated list of images with their metadata and tags
      operationId: listImages
      tags:
        - Gallery
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          description: Sort order
          schema:
            type: string
            enum: [name-asc, name-desc, date-asc, date-desc]
        - name: tag
          in: query
          description: Filter by tag
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved images
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedImageResponse'

  /gallery/images/{imageName}:
    get:
      summary: Get image details
      description: Returns details for a specific image
      operationId: getImage
      tags:
        - Gallery
      parameters:
        - name: imageName
          in: path
          required: true
          description: Name of the image
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved image
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageDetail'
        '404':
          description: Image not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /gallery/batch-images:
    post:
      summary: Batch process images
      description: Process multiple images at once
      operationId: batchProcessImages
      tags:
        - Gallery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Successfully processed images
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchProcessResponse'

  /blog/api/posts:
    get:
      summary: List blog posts
      description: Returns a list of blog posts
      operationId: listPosts
      tags:
        - Blog
      responses:
        '200':
          description: Successfully retrieved posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostList'
    
    post:
      summary: Create blog post
      description: Creates a new blog post
      operationId: createPost
      tags:
        - Blog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCreate'
      responses:
        '201':
          description: Successfully created post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

  /proxy/image/preview:
    get:
      summary: Get image preview
      description: Returns a preview version of an image
      operationId: getImagePreview
      tags:
        - Media
      parameters:
        - name: image_name
          in: query
          required: true
          description: Name of the image
          schema:
            type: string
      responses:
        '200':
          description: Image preview
          content:
            image/*:
              schema:
                type: string
                format: binary

components:
  schemas:
    PaginatedImageResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ImageDetail'
        total:
          type: integer
        page:
          type: integer
        totalPages:
          type: integer
        pageSize:
          type: integer
      required:
        - items
        - total
        - page
        - totalPages
        - pageSize

    ImageDetail:
      type: object
      properties:
        name:
          type: string
        path:
          type: string
        size:
          type: integer
        modifiedDate:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string
        type:
          type: string
        dimensions:
          type: object
          properties:
            width:
              type: integer
            height:
              type: integer
      required:
        - name
        - path
        - size
        - modifiedDate

    BatchProcessResponse:
      type: object
      properties:
        processed:
          type: array
          items:
            type: string
        failed:
          type: array
          items:
            type: string
        processingTime:
          type: number
      required:
        - processed
        - failed
        - processingTime

    PostList:
      type: array
      items:
        $ref: '#/components/schemas/Post'

    Post:
      type: object
      properties:
        title:
          type: string
        path:
          type: string
        content:
          type: string
        date:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string
      required:
        - title
        - path
        - content
        - date

    PostCreate:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        tags:
          type: array
          items:
            type: string
      required:
        - title
        - content

    Error:
      type: object
      properties:
        error:
          type: string
        code:
          type: string
      required:
        - error
